// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///  options: DefaultFirebaseOptions.currentPlatform,
///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE70TBmPvJO30Rkp3RQC8nZCKzpywUnzU',
    appId: '1:802595696845:web:28e9855e2169e1b38af984',
    messagingSenderId: '802595696845',
    projectId: 'localevents-53e86',
    authDomain: 'localevents-53e86.firebaseapp.com',
    storageBucket: 'localevents-53e86.firebasestorage.app',
    measurementId: 'G-BY0EJBD7QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uhROT-qesoJrdFmbnNs6PABo6K88Hdk',
    appId: '1:802595696845:android:2c16b7f587536b868af984',
    messagingSenderId: '802595696845',
    projectId: 'localevents-53e86',
    storageBucket: 'localevents-53e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK1zfhknD5IzLEUJA28HEk75kzIbrXxsA',
    appId: '1:802595696845:ios:be5a62d4fed3f61d8af984',
    messagingSenderId: '802595696845',
    projectId: 'localevents-53e86',
    storageBucket: 'localevents-53e86.firebasestorage.app',
    iosBundleId: 'com.example.localEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK1zfhknD5IzLEUJA28HEk75kzIbrXxsA',
    appId: '1:802595696845:ios:be5a62d4fed3f61d8af984',
    messagingSenderId: '802595696845',
    projectId: 'localevents-53e86',
    storageBucket: 'localevents-53e86.firebasestorage.app',
    iosBundleId: 'com.example.localEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE70TBmPvJO30Rkp3RQC8nZCKzpywUnzU',
    appId: '1:802595696845:web:95ef8f4023e6fec78af984',
    messagingSenderId: '802595696845',
    projectId: 'localevents-53e86',
    authDomain: 'localevents-53e86.firebaseapp.com',
    storageBucket: 'localevents-53e86.firebasestorage.app',
    measurementId: 'G-JY8C7LXCLF',
  );
}
